properties([
  pipelineTriggers([
    pollSCM('', [
      includeregions: 'service_1/.*'
    ])
  ])
])
pipeline {
    agent any
    stages{
        stage("build")
        {
            steps{
                echo "Building the project 11..."
            }
        }
    }

}
