pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    triggers {
        githubPush()     // GitHub webhook trigger
    }

  stages{
        stage("checkout"){
            steps{
            echo "code checkout"
            checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'bhavanachoudhari24', url: 'https://github.com/bhavanachoudhari24/Multiple-pipeline.git']])
            echo "code checkout successful-11"
        }}

        stage('Build Only If service_2 Changed') {
            when {
                changeset "service_2/**"
            }
            steps {
                echo "Building the project 2 because service_2 changed..."
            }
        }
        stage('Skip logic') {
            when { not { changeset "service_2/**" } }
            steps {
                echo "No changes in service_2 — pipeline will end"
            }
       }
    }
}