properties([
  pipelineTriggers([
    pollSCM('', [
      includeregions: 'service_2/.*'
    ])
  ])
])
pipeline{
    agent any
    stages{
        stage("build")
        {
            steps{
                echo "Building the project 2..."
            }
        }
    }

}
